name: deploy-storage-rules
run-name: Deploy storage rules
on:
    pull_request:
        paths:
            - storage.rules
        branches:
            - main
jobs:
    deploy-firebase-rules:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "yarn"
                  cache-dependency-path: "**/yarn.lock"
            - run: yarn install --frozen-lockfile --prefer-offline
            - run: yarn firebase deploy --only storage --debug --project regov-user-portal --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}"
